### PR TITLE
Adjusted the hud and added enemy count

### PR DESCRIPTION
**Pull request by FaizanJavair**

### CODE REVIEW

**Comment by safwanrahman** [comment]
@FaizanJavair Seems like this PR breaks the HudScene.

Screenshot 2023-09-15 at 3 14 38 AM
Screenshot 2023-09-15 at 3 15 26 AM


In Main branch, it is like following as expected:

Screenshot 2023-09-15 at 3 18 20 AM

**Comment by FaizanJavair** [comment]
I am not sure why this is happening. The main branch had multiple inconsistencies with the positioning with the HUD Scene and most of them are readjusted accordingly.

NVIDIA_Share_qgswRReu91

Everything locally works as expected and is also rebased with main

**Comment by safwanrahman** [comment]
@FaizanJavair That is weired. I have cleared the cache as well as the Library Folder to check if this is cache issue, but still I got same result. I have made the fixes, can you fetch my commit and cherry pick my commit 4bc4fd789919c11924e788035a75479cbd3d68c3 to check if it is working properly?

You can do following
```
git fetch --all
git cherry pick 4bc4fd789919c11924e788035a75479cbd3d68c3
```

**Review by neveensakr — APPROVED** [review]
👍

**Pull request merged**
